// <auto-generated />
using System;
using InlibrisVeritas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InlibrisVeritas.Migrations
{
    [DbContext(typeof(BloggDbContext))]
    partial class BloggDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InlibrisVeritas.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Här kommer lite innehåll i inlägget",
                            Created = new DateTime(2020, 3, 9, 13, 19, 1, 387, DateTimeKind.Utc).AddTicks(403),
                            ImageUrl = "http://studenter.miun.se/~ella1800/dt102g/img/brazil.jpg",
                            Title = "Möss och människor"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Här kommer lite innehåll i inlägget",
                            Created = new DateTime(2020, 3, 9, 13, 19, 1, 388, DateTimeKind.Utc).AddTicks(7945),
                            ImageUrl = "http://studenter.miun.se/~ella1800/dt102g/img/brazil.jpg",
                            Title = "Aniara"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
